type: app
description: Default stackfile usecase description
# template used to create the project
template: stack-poc/template-poc-1
inputs:
  some_input: value
# list of plugins to be applied after project creation
plugins:
  - plugin: stack-poc/plugin-1
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
